
- hosts: localhost

  tasks: 

  - name Install pip module hpOneView
    pip:
      name: hpOneView
      umask: "0022"

  - name Install pip module hpICsp
    pip:
      name: hpICsp
      umask: "0022"

  - name Install pip module python-hpilo
    pip:
      name: python-hpilo
      umask: "0022"
