 
---
- hosts: localhost
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
      user_name: nobody
  
  tasks:
    - name: Gather facts about user
      oneview_user_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=users


